name: Deploy to Firebase
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install packages
        run: yarn install

      - name: Lint files
        run: yarn run lint

      - name: Unitary Tests
        run: yarn run test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build project
        run: yarn run build

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIRCALL_CDC1D }}'
          channelId: live
          projectId: aircall-cdc1d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
